version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/techwired/
permissions:
  - object: home/ec2-user/techwired/
    owner: root
    mode: 4755
    type:
      - directory
  - object: scripts/install-dependencies.sh
    owner: root
    mode: 4755
    type:
      - file

hooks:
  AfterInstall:
    - location: scripts/install-dependencies.sh
      runas: root