version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/
permissions:
  - object: home/ec2-user/app/
    owner: root
    mode: 4755
    type:
      - directory
  - object: scripts/install-dependencies.sh
    owner: root
    mode: 4755
    type:
      - file
  - object: scripts/app-start.sh
    owner: root
    mode: 4755
    type:
      - file
  - object: scripts/app-end.sh
    owner: root
    mode: 4755
    type:
      - file

hooks:
  AfterInstall:
    - location: scripts/install-dependencies.sh
      runas: root
  ApplicationStart:
    - location: scripts/app-start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/app-end.sh
      timeout: 300
      runas: root