version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2/app/
  - source: /scripts/app.service
    destination: /etc/systemd/system/
permissions:
  - object: home/ec2/app/scripts/install_dependencies.sh
    owner: root
    mode: 755
    type:
      - file
  - object: home/ec2/app/scripts/start_app.sh
    owner: root
    mode: 755
    type:
      - file
  - object: home/ec2/app/scripts/stop_app.sh
    owner: root
    mode: 755
    type:
      - file

hooks:
  AfterInstall:
    - location: home/ec2/app/scripts/install_dependencies.sh
      runas: root
  ApplicationStart:
    - location: home/ec2/app/scripts/start_app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: home/ec2/app/scripts/stop_app.sh
      timeout: 300
      runas: root