version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo Starting the build stage
      - sudo apt-get update
      - pyenv exec python -m venv .venv
      - .venv/Scripts/activate
      - pip install -r requirements.txt
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - blogging
    - requirements.txt